# Generated by Django 6.0.1 on 2026-02-04 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0004_alter_company_options_alter_locality_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='partner_id',
            field=models.CharField(blank=True, editable=False, help_text='Auto-generated ID', max_length=20, unique=True),
        ),
    ]
