# Generated by Django 6.0.1 on 2026-02-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0005_company_partner_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenspecpack',
            name='active_hours_per_day',
            field=models.IntegerField(help_text='Hours screen runs daily'),
        ),
        migrations.AlterField(
            model_name='screenspecpack',
            name='ai_camera_installed',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='screenspecpack',
            name='allowed_durations_sec',
            field=models.JSONField(help_text='List of allowed durations e.g., [10,15,20,30]'),
        ),
        migrations.AlterField(
            model_name='screenspecpack',
            name='audio_supported',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='screenspecpack',
            name='average_bandwidth_mbps',
            field=models.IntegerField(choices=[(10, '10 Mbps'), (25, '25 Mbps'), (50, '50 Mbps'), (100, '100 Mbps'), (200, '200 Mbps')]),
        ),
        migrations.AlterField(
            model_name='screenspecpack',
            name='backup_internet',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='screenspecpack',
            name='brightness_nits',
            field=models.IntegerField(help_text='Brightness in nits'),
        ),
        migrations.AlterField(
            model_name='screenspecpack',
            name='content_policy_accepted',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='screenspecpack',
            name='days_active_per_week',
            field=models.JSONField(help_text="List of active days e.g., ['Mon','Tue'...]"),
        ),
        migrations.AlterField(
            model_name='screenspecpack',
            name='internet_type',
            field=models.CharField(choices=[('FIBER', 'Fiber'), ('BROADBAND', 'Broadband'), ('4G', '4G'), ('5G', '5G'), ('WIFI', 'WiFi')], max_length=20),
        ),
        migrations.AlterField(
            model_name='screenspecpack',
            name='loop_length_sec',
            field=models.IntegerField(help_text='Total loop length in seconds'),
        ),
        migrations.AlterField(
            model_name='screenspecpack',
            name='max_file_size_mb',
            field=models.IntegerField(choices=[(50, '50 MB'), (100, '100 MB'), (200, '200 MB'), (500, '500 MB')]),
        ),
        migrations.AlterField(
            model_name='screenspecpack',
            name='minimum_booking_days',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='screenspecpack',
            name='partner_cms_api_support',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='screenspecpack',
            name='pixel_pitch_mm',
            field=models.DecimalField(decimal_places=2, help_text='Pixel pitch in mm', max_digits=5),
        ),
        migrations.AlterField(
            model_name='screenspecpack',
            name='playback_logs_available',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='screenspecpack',
            name='power_backup_type',
            field=models.CharField(choices=[('NONE', 'None'), ('UPS', 'UPS'), ('GENERATOR', 'Generator'), ('UPS_AND_GENERATOR', 'UPS + Generator')], max_length=20),
        ),
        migrations.AlterField(
            model_name='screenspecpack',
            name='proof_of_play_supported',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='screenspecpack',
            name='refresh_rate_hz',
            field=models.IntegerField(choices=[(30, '30 Hz'), (60, '60 Hz'), (120, '120 Hz')]),
        ),
        migrations.AlterField(
            model_name='screenspecpack',
            name='reserved_slots',
            field=models.IntegerField(help_text='Slots reserved for own content'),
        ),
        migrations.AlterField(
            model_name='screenspecpack',
            name='restricted_categories',
            field=models.JSONField(help_text='List of restricted ad categories'),
        ),
        migrations.AlterField(
            model_name='screenspecpack',
            name='screen_health_ping',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='screenspecpack',
            name='seasonal_pricing',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='screenspecpack',
            name='sensitive_zone_flags',
            field=models.JSONField(help_text='Sensitive locations nearby'),
        ),
        migrations.AlterField(
            model_name='screenspecpack',
            name='standard_ad_duration_sec',
            field=models.IntegerField(choices=[(5, '5s'), (10, '10s'), (15, '15s'), (20, '20s'), (30, '30s'), (60, '60s')]),
        ),
        migrations.AlterField(
            model_name='screenspecpack',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('active', 'Active')], max_length=20),
        ),
        migrations.AlterField(
            model_name='screenspecpack',
            name='supported_formats',
            field=models.JSONField(help_text='List of supported formats'),
        ),
        migrations.AlterField(
            model_name='screenspecpack',
            name='total_slots_per_loop',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='screenspecpack',
            name='uptime_target_percent',
            field=models.IntegerField(choices=[(95, '95%'), (97, '97%'), (99, '99%'), (995, '99.5%'), (999, '99.9%')]),
        ),
        migrations.AlterField(
            model_name='screenspecpack',
            name='viewing_angle_degrees',
            field=models.IntegerField(blank=True, editable=False, help_text='Auto: fixed 140°', null=True),
        ),
    ]
