# Generated by Django 6.0.1 on 2026-02-04 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0006_alter_screenspecpack_active_hours_per_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenspecpack',
            name='recommended_viewing_distance_m',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Auto: pixel_pitch_mm = distance in meters (e.g., 10mm = 10m)', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='screenspecpack',
            name='viewing_angle_degrees',
            field=models.IntegerField(default=140, help_text='Viewing angle in degrees (90-180)'),
            preserve_default=False,
        ),
    ]
