# Generated by Django 6.0.1 on 2026-02-04 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0007_alter_screenspecpack_recommended_viewing_distance_m_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenspecpack',
            name='recommended_viewing_distance_m',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Optimal viewing distance in meters', max_digits=6),
            preserve_default=False,
        ),
    ]
