# Generated by Django 6.0.1 on 2026-02-04 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0008_alter_screenspecpack_recommended_viewing_distance_m'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screenspecpack',
            name='partner',
        ),
        migrations.AddField(
            model_name='screenspecpack',
            name='partner_id',
            field=models.CharField(blank=True, editable=False, help_text='Auto-generated Partner ID', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='screenspecpack',
            name='screen_id',
            field=models.CharField(blank=True, editable=False, help_text='Auto-generated ID', max_length=50, unique=True),
        ),
    ]
