# Generated by Django 6.0.1 on 2026-02-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0009_remove_screenspecpack_partner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenspecpack',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('active', 'Active')], default='draft', max_length=20),
        ),
    ]
