# Generated by Django 6.0.1 on 2026-02-04 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0010_alter_screenspecpack_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenspecpack',
            name='camera_model_other',
            field=models.CharField(blank=True, help_text="Specify if 'Other' is selected", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='screenspecpack',
            name='seasonal_pricing_details',
            field=models.JSONField(blank=True, help_text="If seasonal pricing enabled, e.g., {'Diwali': 1.5, 'Summer': 0.8} as multipliers", null=True),
        ),
    ]
