# Generated by Django 6.0.1 on 2026-02-04 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0011_screenspecpack_camera_model_other_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenspecpack',
            name='freeform_values',
            field=models.JSONField(blank=True, help_text="Custom values when Freeform is selected, e.g., {'screen_type': 'Digital Kiosk', 'internet_type': 'Starlink'}", null=True),
        ),
        migrations.AlterField(
            model_name='screenspecpack',
            name='average_bandwidth_mbps',
            field=models.IntegerField(choices=[(0, 'None'), (10, '10 Mbps'), (25, '25 Mbps'), (50, '50 Mbps'), (100, '100 Mbps'), (200, '200 Mbps'), (-1, 'Freeform')]),
        ),
        migrations.AlterField(
            model_name='screenspecpack',
            name='booking_type',
            field=models.CharField(choices=[('NONE', 'None'), ('SOLO', 'Solo'), ('BUNDLE_ONLY', 'Bundle Only'), ('BOTH', 'Both'), ('FREEFORM', 'Freeform')], max_length=20),
        ),
        migrations.AlterField(
            model_name='screenspecpack',
            name='cms_type',
            field=models.CharField(choices=[('NONE', 'None'), ('XIGI_CMS', 'Xigi CMS'), ('PARTNER_CMS', 'Partner CMS'), ('FREEFORM', 'Freeform')], max_length=50),
        ),
        migrations.AlterField(
            model_name='screenspecpack',
            name='facing_direction',
            field=models.CharField(choices=[('N', 'North'), ('NE', 'North-East'), ('E', 'East'), ('SE', 'South-East'), ('S', 'South'), ('SW', 'South-West'), ('W', 'West'), ('NW', 'North-West'), ('FREEFORM', 'Freeform')], max_length=20),
        ),
        migrations.AlterField(
            model_name='screenspecpack',
            name='installation_type',
            field=models.CharField(choices=[('ROOFTOP', 'Rooftop'), ('WALL_MOUNTED', 'Wall Mounted'), ('POLE_MOUNTED', 'Pole Mounted'), ('GROUND_LEVEL', 'Ground Level'), ('INDOOR_MALL', 'Indoor Mall'), ('INDOOR_AIRPORT', 'Indoor Airport'), ('INDOOR_STATION', 'Indoor Station'), ('INDOOR_OTHER', 'Indoor Other'), ('FREEFORM', 'Freeform')], max_length=50),
        ),
        migrations.AlterField(
            model_name='screenspecpack',
            name='internet_type',
            field=models.CharField(choices=[('NONE', 'None'), ('FIBER', 'Fiber'), ('BROADBAND', 'Broadband'), ('4G', '4G'), ('5G', '5G'), ('WIFI', 'WiFi'), ('FREEFORM', 'Freeform')], max_length=50),
        ),
        migrations.AlterField(
            model_name='screenspecpack',
            name='max_file_size_mb',
            field=models.IntegerField(choices=[(0, 'None'), (50, '50 MB'), (100, '100 MB'), (200, '200 MB'), (500, '500 MB'), (-1, 'Freeform')]),
        ),
        migrations.AlterField(
            model_name='screenspecpack',
            name='obstruction_risk',
            field=models.CharField(choices=[('NONE', 'None'), ('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('FREEFORM', 'Freeform')], max_length=20),
        ),
        migrations.AlterField(
            model_name='screenspecpack',
            name='partner_cms_brand',
            field=models.CharField(blank=True, choices=[('NONE', 'None'), ('Broadsign', 'Broadsign'), ('Scala', 'Scala'), ('Signagelive', 'Signagelive'), ('Screenly', 'Screenly'), ('Other', 'Other'), ('FREEFORM', 'Freeform')], help_text='Required if Partner CMS', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='screenspecpack',
            name='power_backup_type',
            field=models.CharField(choices=[('NONE', 'None'), ('UPS', 'UPS'), ('GENERATOR', 'Generator'), ('UPS_AND_GENERATOR', 'UPS + Generator'), ('FREEFORM', 'Freeform')], max_length=50),
        ),
        migrations.AlterField(
            model_name='screenspecpack',
            name='refresh_rate_hz',
            field=models.IntegerField(choices=[(30, '30 Hz'), (60, '60 Hz'), (120, '120 Hz'), (0, 'Freeform')]),
        ),
        migrations.AlterField(
            model_name='screenspecpack',
            name='road_type',
            field=models.CharField(choices=[('HIGHWAY', 'Highway'), ('ARTERIAL', 'Arterial'), ('COLLECTOR', 'Collector'), ('LOCAL', 'Local'), ('INTERNAL', 'Internal'), ('FREEFORM', 'Freeform')], max_length=50),
        ),
        migrations.AlterField(
            model_name='screenspecpack',
            name='screen_type',
            field=models.CharField(choices=[('LED', 'LED'), ('LCD', 'LCD'), ('PROJECTION', 'Projection'), ('FREEFORM', 'Freeform')], max_length=50),
        ),
        migrations.AlterField(
            model_name='screenspecpack',
            name='standard_ad_duration_sec',
            field=models.IntegerField(choices=[(0, 'None'), (5, '5s'), (10, '10s'), (15, '15s'), (20, '20s'), (30, '30s'), (60, '60s'), (-1, 'Freeform')]),
        ),
        migrations.AlterField(
            model_name='screenspecpack',
            name='traffic_direction',
            field=models.CharField(choices=[('NONE', 'None'), ('ONE_WAY', 'One Way'), ('BOTH_WAYS', 'Both Ways'), ('FREEFORM', 'Freeform')], max_length=20),
        ),
        migrations.AlterField(
            model_name='screenspecpack',
            name='uptime_target_percent',
            field=models.IntegerField(choices=[(0, 'None'), (95, '95%'), (97, '97%'), (99, '99%'), (995, '99.5%'), (999, '99.9%'), (-1, 'Freeform')]),
        ),
    ]
