# Generated by Django 6.0.1 on 2026-02-04 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0012_screenspecpack_freeform_values_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenspecpack',
            name='facing_direction',
            field=models.CharField(choices=[('NONE', 'None'), ('N', 'North'), ('NE', 'North-East'), ('E', 'East'), ('SE', 'South-East'), ('S', 'South'), ('SW', 'South-West'), ('W', 'West'), ('NW', 'North-West'), ('FREEFORM', 'Freeform')], max_length=20),
        ),
        migrations.AlterField(
            model_name='screenspecpack',
            name='installation_type',
            field=models.CharField(choices=[('NONE', 'None'), ('ROOFTOP', 'Rooftop'), ('WALL_MOUNTED', 'Wall Mounted'), ('POLE_MOUNTED', 'Pole Mounted'), ('GROUND_LEVEL', 'Ground Level'), ('INDOOR_MALL', 'Indoor Mall'), ('INDOOR_AIRPORT', 'Indoor Airport'), ('INDOOR_STATION', 'Indoor Station'), ('INDOOR_OTHER', 'Indoor Other'), ('FREEFORM', 'Freeform')], max_length=50),
        ),
        migrations.AlterField(
            model_name='screenspecpack',
            name='refresh_rate_hz',
            field=models.IntegerField(choices=[(-2, 'None'), (30, '30 Hz'), (60, '60 Hz'), (120, '120 Hz'), (-1, 'Freeform')]),
        ),
        migrations.AlterField(
            model_name='screenspecpack',
            name='road_type',
            field=models.CharField(choices=[('NONE', 'None'), ('HIGHWAY', 'Highway'), ('ARTERIAL', 'Arterial'), ('COLLECTOR', 'Collector'), ('LOCAL', 'Local'), ('INTERNAL', 'Internal'), ('FREEFORM', 'Freeform')], max_length=50),
        ),
        migrations.AlterField(
            model_name='screenspecpack',
            name='screen_type',
            field=models.CharField(choices=[('NONE', 'None'), ('LED', 'LED'), ('LCD', 'LCD'), ('PROJECTION', 'Projection'), ('FREEFORM', 'Freeform')], max_length=50),
        ),
    ]
