# Generated by Django 6.0.1 on 2026-02-04 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0013_alter_screenspecpack_facing_direction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screenspecpack',
            name='camera_model_other',
        ),
        migrations.RemoveField(
            model_name='screenspecpack',
            name='freeform_values',
        ),
        migrations.AlterField(
            model_name='screenspecpack',
            name='average_bandwidth_mbps',
            field=models.IntegerField(help_text='e.g., 10, 25, 50, 100, 200'),
        ),
        migrations.AlterField(
            model_name='screenspecpack',
            name='booking_type',
            field=models.CharField(help_text='e.g., Solo, Bundle Only, Both', max_length=50),
        ),
        migrations.AlterField(
            model_name='screenspecpack',
            name='camera_model',
            field=models.CharField(blank=True, help_text='e.g., Quividi, AdMobilize, Linkett', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='screenspecpack',
            name='cms_type',
            field=models.CharField(help_text='e.g., Xigi CMS, Partner CMS', max_length=50),
        ),
        migrations.AlterField(
            model_name='screenspecpack',
            name='facing_direction',
            field=models.CharField(help_text='e.g., North, North-East, East', max_length=50),
        ),
        migrations.AlterField(
            model_name='screenspecpack',
            name='installation_type',
            field=models.CharField(help_text='e.g., Rooftop, Wall Mounted, Indoor Mall', max_length=50),
        ),
        migrations.AlterField(
            model_name='screenspecpack',
            name='internet_type',
            field=models.CharField(help_text='e.g., Fiber, Broadband, 4G, 5G, WiFi', max_length=50),
        ),
        migrations.AlterField(
            model_name='screenspecpack',
            name='max_file_size_mb',
            field=models.IntegerField(help_text='e.g., 50, 100, 200, 500'),
        ),
        migrations.AlterField(
            model_name='screenspecpack',
            name='obstruction_risk',
            field=models.CharField(help_text='e.g., None, Low, Medium, High', max_length=50),
        ),
        migrations.AlterField(
            model_name='screenspecpack',
            name='partner_cms_brand',
            field=models.CharField(blank=True, help_text='e.g., Broadsign, Scala, Signagelive', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='screenspecpack',
            name='power_backup_type',
            field=models.CharField(help_text='e.g., None, UPS, Generator, UPS + Generator', max_length=50),
        ),
        migrations.AlterField(
            model_name='screenspecpack',
            name='refresh_rate_hz',
            field=models.IntegerField(help_text='e.g., 30, 60, 120'),
        ),
        migrations.AlterField(
            model_name='screenspecpack',
            name='road_type',
            field=models.CharField(help_text='e.g., Highway, Arterial, Local', max_length=50),
        ),
        migrations.AlterField(
            model_name='screenspecpack',
            name='screen_type',
            field=models.CharField(help_text='e.g., LED, LCD, Projection, OLED', max_length=50),
        ),
        migrations.AlterField(
            model_name='screenspecpack',
            name='standard_ad_duration_sec',
            field=models.IntegerField(help_text='e.g., 5, 10, 15, 20, 30, 60'),
        ),
        migrations.AlterField(
            model_name='screenspecpack',
            name='traffic_direction',
            field=models.CharField(help_text='e.g., One Way, Both Ways', max_length=50),
        ),
        migrations.AlterField(
            model_name='screenspecpack',
            name='uptime_target_percent',
            field=models.IntegerField(help_text='e.g., 95, 97, 99'),
        ),
    ]
