# Generated by Django 6.0.1 on 2026-02-04 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0014_remove_screenspecpack_camera_model_other_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenspecpack',
            name='cms_api_endpoint',
            field=models.URLField(blank=True, help_text='API endpoint to fetch media player details automatically', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='screenspecpack',
            name='day_visibility_rating',
            field=models.IntegerField(default=5, help_text='Rate visibility during day (1-10)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='screenspecpack',
            name='media_player_id',
            field=models.CharField(blank=True, editable=False, help_text='Auto-fetched from CMS API', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='screenspecpack',
            name='media_player_model',
            field=models.CharField(blank=True, editable=False, help_text='Auto-fetched from CMS API', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='screenspecpack',
            name='night_visibility_rating',
            field=models.IntegerField(default=5, help_text='Rate visibility during night (1-10)'),
            preserve_default=False,
        ),
    ]
