# Generated by Django 6.0.1 on 2026-02-06 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0015_screenspecpack_cms_api_endpoint_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screenspecpack',
            name='partner_cms_brand',
        ),
        migrations.AddField(
            model_name='screenspecpack',
            name='cms_brand',
            field=models.CharField(blank=True, editable=False, help_text='Auto-fetched from CMS API', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='screenspecpack',
            name='cms_type',
            field=models.CharField(blank=True, editable=False, help_text='Auto-fetched from CMS API', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='screenspecpack',
            name='ownership_proof_uploaded',
            field=models.FileField(blank=True, null=True, upload_to='console/Docs/'),
        ),
        migrations.AlterField(
            model_name='screenspecpack',
            name='partner_cms_api_support',
            field=models.BooleanField(default=False, help_text='Auto-set to True when CMS API endpoint is provided'),
        ),
        migrations.AlterField(
            model_name='screenspecpack',
            name='permission_noc_available',
            field=models.FileField(blank=True, null=True, upload_to='console/Docs/'),
        ),
    ]
