# Generated by Django 6.0.1 on 2026-02-06 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0016_remove_screenspecpack_partner_cms_brand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screenspecpack',
            name='created_by',
        ),
        migrations.AddField(
            model_name='screenspecpack',
            name='console_login',
            field=models.ForeignKey(blank=True, help_text='Admin user who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_screens', to=settings.AUTH_USER_MODEL),
        ),
    ]
