# Generated by Django 6.0.1 on 2026-02-10 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0018_screenspec_delete_screenspecpack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenspec',
            name='road_type',
            field=models.CharField(blank=True, help_text='e.g. Highway, Arterial, or Custom', max_length=100),
        ),
        migrations.AlterField(
            model_name='screenspec',
            name='screen_type',
            field=models.CharField(default='Video Wall', help_text='e.g. Video Wall, Transparent LED, or Custom', max_length=100),
        ),
    ]
