# Generated by Django 6.0.1 on 2026-02-11 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0019_alter_screenspec_road_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenspec',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
