# Generated by Django 6.0.1 on 2026-02-11 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0020_alter_screenspec_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenspec',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('VERIFIED', 'Verified')], default='DRAFT', max_length=20),
        ),
    ]
