# Generated by Django 6.0.1 on 2026-02-11 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0023_customuser_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenspec',
            name='enable_surcharge',
            field=models.BooleanField(default=False),
        ),
    ]
