# Generated by Django 6.0.1 on 2026-02-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0024_screenspec_enable_surcharge'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenspec',
            name='current_step',
            field=models.IntegerField(default=1, help_text='Last completed/active step in onboarding'),
        ),
    ]
