# Generated by Django 6.0.1 on 2026-02-11 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0025_screenspec_current_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenspec',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='screenspec',
            name='screen_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
