# Generated by Django 6.0.1 on 2026-02-11 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0026_alter_screenspec_city_alter_screenspec_screen_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screenspec',
            name='min_viewing_distance_meters',
        ),
        migrations.RemoveField(
            model_name='screenspec',
            name='viewing_angle',
        ),
    ]
