# Generated by Django 6.0.1 on 2026-02-12 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0027_remove_screenspec_min_viewing_distance_meters_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenspec',
            name='surcharge_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
