# Generated by Django 6.0.1 on 2026-02-12 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0028_screenspec_surcharge_percent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='screenspec',
            old_name='partner_gst',
            new_name='gst',
        ),
        migrations.RenameField(
            model_name='screenspec',
            old_name='partner_id',
            new_name='uid',
        ),
        migrations.RemoveField(
            model_name='screenspec',
            name='partner_cms_api',
        ),
        migrations.AddField(
            model_name='screenspec',
            name='cms_api',
            field=models.CharField(blank=True, help_text='CMS API endpoint', max_length=255),
        ),
    ]
