# Generated by Django 6.0.1 on 2026-02-12 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0029_rename_partner_gst_screenspec_gst_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenspec',
            name='road_type',
            field=models.CharField(blank=True, help_text='e.g. Highway, Arterial, or Custom', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='screenspec',
            name='traffic_direction',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
