# Generated by Django 6.0.1 on 2026-02-12 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0030_alter_screenspec_road_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenspec',
            name='is_profiled',
            field=models.BooleanField(default=False),
        ),
    ]
