# Generated by Django 6.0.1 on 2026-02-13 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0031_screenspec_is_profiled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenspec',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20),
        ),
    ]
