# Generated by Django 6.0.1 on 2026-02-13 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0032_alter_screenspec_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenspec',
            name='source',
            field=models.CharField(choices=[('INTERNAL', 'Internal'), ('EXTERNAL', 'External')], default='INTERNAL', help_text='Where the screen data came from', max_length=20),
        ),
        migrations.AlterField(
            model_name='screenspec',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20),
        ),
    ]
