# Generated by Django 6.0.1 on 2026-02-14 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0033_screenspec_source_alter_screenspec_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenspec',
            name='booked_slots',
            field=models.IntegerField(default=0, help_text='Slots currently booked by advertisers'),
        ),
    ]
