# Generated by Django 6.0.1 on 2026-02-14 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0034_screenspec_booked_slots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screenspec',
            name='booked_slots',
        ),
        migrations.CreateModel(
            name='SlotBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_slots', models.IntegerField(help_text='Number of slots booked')),
                ('start_date', models.DateField(help_text='Booking start date')),
                ('end_date', models.DateField(help_text='Booking end date')),
                ('campaign_id', models.CharField(blank=True, help_text='Campaign reference', max_length=100)),
                ('user_id', models.CharField(blank=True, help_text='Advertiser identifier', max_length=100)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_bookings', to='console.screenspec')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
