# Generated by Django 6.0.1 on 2026-02-14 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0035_remove_screenspec_booked_slots_slotbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotbooking',
            name='source',
            field=models.CharField(choices=[('XIGI', 'Xigi Platform Booking'), ('PARTNER', 'Partner Direct Block')], default='XIGI', help_text='Who created this booking', max_length=20),
        ),
    ]
