# Generated by Django 6.0.1 on 2026-02-16 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0036_slotbooking_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenspec',
            name='remarks',
            field=models.TextField(blank=True, default='', help_text='Review remarks (rejection reason, etc.)'),
        ),
        migrations.AddField(
            model_name='screenspec',
            name='reviewed_by',
            field=models.CharField(blank=True, default='', help_text='Who reviewed this screen', max_length=100),
        ),
    ]
