# Generated by Django 6.0.1 on 2026-02-17 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0037_screenspec_remarks_screenspec_reviewed_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreenImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='screen_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='console.screenspec')),
            ],
        ),
    ]
