# Generated by Django 6.0.1 on 2026-02-17 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0038_screenimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenspec',
            name='screen_image_back',
            field=models.ImageField(blank=True, null=True, upload_to='screens/back/'),
        ),
        migrations.AddField(
            model_name='screenspec',
            name='screen_image_front',
            field=models.ImageField(blank=True, null=True, upload_to='screens/front/'),
        ),
        migrations.AddField(
            model_name='screenspec',
            name='screen_image_long',
            field=models.ImageField(blank=True, null=True, upload_to='screens/long/'),
        ),
        migrations.DeleteModel(
            name='ScreenImage',
        ),
    ]
