# Generated by Django 6.0.1 on 2026-02-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0039_screenspec_screen_image_back_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotbooking',
            name='payment',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('PAID', 'Paid')], default='UNPAID', help_text='Payment status', max_length=20),
        ),
        migrations.AlterField(
            model_name='slotbooking',
            name='status',
            field=models.CharField(choices=[('HOLD', 'Hold'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='HOLD', max_length=20),
        ),
    ]
