# Generated by Django 6.0.1 on 2026-02-19 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0040_slotbooking_payment_alter_slotbooking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenspec',
            name='profile_status',
            field=models.CharField(choices=[('UNPROFILED', 'Unprofiled'), ('PROFILED', 'Profiled'), ('REPROFILE', 'Reprofile')], default='UNPROFILED', max_length=20),
        ),
    ]
