# Generated by Django 6.0.1 on 2026-02-19 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0041_screenspec_profile_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_id', models.IntegerField(help_text='Screen ID from ScreenSpec (cross-ref, not Django FK)')),
                ('screen_name', models.CharField(blank=True, default='', max_length=255)),
                ('screen_location', models.CharField(blank=True, default='', max_length=255)),
                ('slot_number', models.IntegerField(help_text='Slot number on this screen (1, 2, 3...)')),
                ('req_resolution_width', models.IntegerField(default=0)),
                ('req_resolution_height', models.IntegerField(default=0)),
                ('req_orientation', models.CharField(blank=True, default='', max_length=20)),
                ('req_max_duration_sec', models.IntegerField(default=0)),
                ('req_max_file_size_mb', models.IntegerField(default=0)),
                ('req_supported_formats', models.JSONField(default=list)),
                ('req_audio_supported', models.BooleanField(default=False)),
                ('file', models.FileField(blank=True, null=True, upload_to='campaign_assets/')),
                ('original_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('file_type', models.CharField(blank=True, max_length=100, null=True)),
                ('file_extension', models.CharField(blank=True, max_length=20, null=True)),
                ('detected_width', models.IntegerField(blank=True, null=True)),
                ('detected_height', models.IntegerField(blank=True, null=True)),
                ('detected_duration_sec', models.FloatField(blank=True, null=True)),
                ('detected_has_audio', models.BooleanField(blank=True, null=True)),
                ('validation_status', models.CharField(choices=[('pending', 'Pending'), ('passed', 'Passed'), ('failed', 'Failed'), ('warning', 'Warning')], default='pending', max_length=20)),
                ('validation_errors', models.JSONField(blank=True, null=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('uploaded', 'Uploaded'), ('validated', 'Validated'), ('approved', 'Approved')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='console.campaign')),
            ],
            options={
                'ordering': ['screen_id', 'slot_number'],
                'unique_together': {('campaign', 'screen_id', 'slot_number')},
            },
        ),
    ]
