# Generated by Django 6.0.1 on 2026-02-19 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0042_campaignasset'),
    ]

    operations = [
        # 1. Remove old unique constraint
        migrations.AlterUniqueTogether(
            name='campaignasset',
            unique_together=set(),
        ),
        # 2. Remove old FK field 'campaign' (its DB column is 'campaign_id')
        migrations.RemoveField(
            model_name='campaignasset',
            name='campaign',
        ),
        # 3. Add the new CharField campaign_id (DB column will also be 'campaign_id')
        migrations.AddField(
            model_name='campaignasset',
            name='campaign_id',
            field=models.CharField(default='', help_text='Campaign ID string e.g. SUM-CHE-001', max_length=100),
            preserve_default=False,
        ),
        # 4. Set new unique constraint with campaign_id CharField
        migrations.AlterUniqueTogether(
            name='campaignasset',
            unique_together={('campaign_id', 'screen_id', 'slot_number')},
        ),
    ]
