# Generated by Django 6.0.1 on 2026-02-20 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0043_alter_campaignasset_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignasset',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('uploaded', 'Uploaded'), ('validated', 'Validated'), ('approved', 'Approved'), ('live', 'Live')], default='pending', max_length=20),
        ),
    ]
