# Generated by Django 6.0.1 on 2026-02-20 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0044_alter_campaignasset_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaignasset',
            name='detected_duration_sec',
        ),
        migrations.RemoveField(
            model_name='campaignasset',
            name='detected_has_audio',
        ),
        migrations.RemoveField(
            model_name='campaignasset',
            name='detected_height',
        ),
        migrations.RemoveField(
            model_name='campaignasset',
            name='detected_width',
        ),
        migrations.AddField(
            model_name='campaignasset',
            name='is_file_format',
            field=models.BooleanField(blank=True, help_text='File format matches supported formats', null=True),
        ),
        migrations.AddField(
            model_name='campaignasset',
            name='is_file_size',
            field=models.BooleanField(blank=True, help_text='File size within max limit', null=True),
        ),
        migrations.AddField(
            model_name='campaignasset',
            name='is_orientation',
            field=models.BooleanField(blank=True, help_text='Orientation matches required specs', null=True),
        ),
        migrations.AddField(
            model_name='campaignasset',
            name='is_resolution',
            field=models.BooleanField(blank=True, help_text='Resolution matches required specs', null=True),
        ),
        migrations.AddField(
            model_name='campaignasset',
            name='is_video_duration',
            field=models.BooleanField(blank=True, help_text='Video duration within max limit', null=True),
        ),
    ]
