# Generated by Django 6.0.1 on 2026-02-20 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0046_alter_campaignasset_is_file_format_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignasset',
            name='is_file_format',
            field=models.BooleanField(default=False, help_text='File format matches supported formats'),
        ),
        migrations.AlterField(
            model_name='campaignasset',
            name='is_file_size',
            field=models.BooleanField(default=False, help_text='File size within max limit'),
        ),
        migrations.AlterField(
            model_name='campaignasset',
            name='is_orientation',
            field=models.BooleanField(default=False, help_text='Orientation matches required specs'),
        ),
        migrations.AlterField(
            model_name='campaignasset',
            name='is_resolution',
            field=models.BooleanField(default=False, help_text='Resolution matches required specs'),
        ),
        migrations.AlterField(
            model_name='campaignasset',
            name='is_video_duration',
            field=models.BooleanField(default=False, help_text='Video duration within max limit'),
        ),
    ]
