# Generated by Django 6.0.1 on 2026-02-23 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0047_alter_campaignasset_is_file_format_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screenspec',
            name='enable_surcharge',
        ),
        migrations.RemoveField(
            model_name='screenspec',
            name='last_minute_charges_json',
        ),
        migrations.RemoveField(
            model_name='screenspec',
            name='proof_of_play_supported',
        ),
        migrations.RemoveField(
            model_name='screenspec',
            name='screen_id',
        ),
        migrations.RemoveField(
            model_name='screenspec',
            name='uid',
        ),
        migrations.AddField(
            model_name='screenspec',
            name='admin_name',
            field=models.CharField(blank=True, help_text='Name of the user who created this screen', max_length=100),
        ),
    ]
