# Generated by Django 6.0.1 on 2026-02-23 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0048_remove_uid_screenid_surcharge_lastminute_pop_add_adminname'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenspec',
            name='scheduled_block_date',
            field=models.DateField(blank=True, help_text='Date when SCHEDULED_BLOCK screen will auto-transition to BLOCKED', null=True),
        ),
        migrations.AlterField(
            model_name='screenspec',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('SCHEDULED_BLOCK', 'Scheduled Block'), ('BLOCKED', 'Blocked')], default='DRAFT', max_length=20),
        ),
    ]
