# Generated by Django 6.0.1 on 2026-02-24 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0049_add_blocked_status_scheduled_block_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotbooking',
            name='notes',
            field=models.TextField(blank=True, default='', help_text="Reason for booking. Partners describe why, Xigi bookings say 'Xigi Campaigns'."),
        ),
    ]
