# Generated by Django 6.0.1 on 2026-02-24 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0050_slotbooking_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotbooking',
            name='status',
            field=models.CharField(choices=[('HOLD', 'Hold'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled'), ('DELETED', 'Deleted')], default='HOLD', max_length=20),
        ),
    ]
