# Generated by Django 6.0.1 on 2026-02-25 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0051_alter_slotbooking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='account_manager',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='agreement_copy',
            field=models.FileField(blank=True, null=True, upload_to='partner_docs/agreements/'),
        ),
        migrations.AddField(
            model_name='company',
            name='api_access_mode',
            field=models.CharField(blank=True, choices=[('push', 'Push'), ('pull', 'Pull')], max_length=10),
        ),
        migrations.AddField(
            model_name='company',
            name='api_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='api_secret',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='api_version',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='auto_approve_screens',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='auto_block_on_api_failure',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='company',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='bank_proof',
            field=models.FileField(blank=True, null=True, upload_to='partner_docs/bank/'),
        ),
        migrations.AddField(
            model_name='company',
            name='base_api_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='billing_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='billing_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='billing_company_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='billing_country',
            field=models.CharField(blank=True, default='India', max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='billing_pincode',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='company',
            name='billing_state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='blacklist_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='contract_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='contract_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='created_by',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='date_joined',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='default_slot_duration',
            field=models.IntegerField(blank=True, help_text='10 / 15 / 30 seconds', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='display_name',
            field=models.CharField(blank=True, help_text='Partner Display Name', max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='escalation_contact',
            field=models.CharField(blank=True, help_text='For screen issues, proof failures, payment disputes, API failures', max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='fixed_cpm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fixed CPM (optional)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='gst_certificate',
            field=models.FileField(blank=True, null=True, upload_to='partner_docs/gst/'),
        ),
        migrations.AddField(
            model_name='company',
            name='gst_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='company',
            name='insurance_document',
            field=models.FileField(blank=True, null=True, upload_to='partner_docs/insurance/'),
        ),
        migrations.AddField(
            model_name='company',
            name='internal_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='internal_rating',
            field=models.IntegerField(blank=True, help_text='Rating 1-5', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='inventory_visibility',
            field=models.CharField(blank=True, choices=[('public', 'Public'), ('private', 'Private'), ('restricted', 'Restricted')], default='public', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='kyc_document',
            field=models.FileField(blank=True, null=True, upload_to='partner_docs/kyc/'),
        ),
        migrations.AddField(
            model_name='company',
            name='last_api_sync_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='last_updated_by',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='manual_verification_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='max_concurrent_campaigns',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='max_screens_allowed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='pan_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='company',
            name='payment_cycle',
            field=models.CharField(blank=True, choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('campaign_based', 'Campaign-based')], max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='primary_contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='primary_contact_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='primary_contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='proof_of_play_mode',
            field=models.CharField(blank=True, choices=[('realtime', 'Real-time'), ('batch', 'Batch'), ('manual_upload', 'Manual Upload')], max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='region_manager',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='revenue_share_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='risk_level',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10),
        ),
        migrations.AddField(
            model_name='company',
            name='secondary_contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='secondary_contact_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='settlement_model',
            field=models.CharField(blank=True, choices=[('revenue_share', 'Revenue Share'), ('fixed_rental', 'Fixed Rental'), ('hybrid', 'Hybrid')], max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='sla_response_time_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='sla_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('onboarding', 'Onboarding'), ('active', 'Active'), ('suspended', 'Suspended'), ('blocked', 'Blocked')], default='onboarding', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='supports_dayparting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='supports_dynamic_creative',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='supports_geo_trigger',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='supports_pop_api',
            field=models.BooleanField(default=False, help_text='Supports Proof of Play API'),
        ),
        migrations.AddField(
            model_name='company',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='company',
            name='webhook_secret',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='webhook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_type',
            field=models.CharField(choices=[('advertiser', 'Advertiser'), ('partner', 'Partner'), ('agency', 'Agency'), ('dooh_network', 'DOOH Network'), ('franchise', 'Franchise'), ('internal', 'Internal')], default='advertiser', max_length=20),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(help_text='Partner Legal Name', max_length=255),
        ),
    ]
