# Generated by Django 6.0.1 on 2026-02-26 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0052_company_account_manager_company_agreement_copy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignasset',
            name='is_resubmission',
            field=models.BooleanField(default=False, help_text='True if this file was re-uploaded after a rejection'),
        ),
    ]
