# Generated by Django 6.0.1 on 2026-02-26 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0053_campaignasset_is_resubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenspec',
            name='role',
            field=models.CharField(choices=[('xigi', 'Xigi'), ('partner', 'Partner'), ('franchise', 'Franchise')], default='xigi', help_text='Screen ownership role', max_length=50),
        ),
    ]
