# Generated by Django 6.0.1 on 2026-02-26 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0054_alter_screenspec_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenspec',
            name='role',
            field=models.CharField(blank=True, choices=[('xigi', 'Xigi'), ('partner', 'Partner'), ('franchise', 'Franchise')], default='', help_text='Screen ownership role', max_length=50),
        ),
    ]
