# Generated by Django 5.2.11 on 2026-02-21 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenmaster',
            name='LLMmode',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='screenmaster',
            name='LLMreason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='screenmaster',
            name='LLMused',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='screenmaster',
            name='apiCallsMade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='screenmaster',
            name='areaContext',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='screenmaster',
            name='cityTier',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='screenmaster',
            name='classificationDetail',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='screenmaster',
            name='computedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='screenmaster',
            name='confidence',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='screenmaster',
            name='dominanceRatio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='screenmaster',
            name='dominantGroup',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='screenmaster',
            name='dwellCategory',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='screenmaster',
            name='dwellConfidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='screenmaster',
            name='dwellScore',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='screenmaster',
            name='movement_context',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='screenmaster',
            name='movement_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='screenmaster',
            name='primaryType',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='screenmaster',
            name='processingTimeMs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='screenmaster',
            name='profiled_city',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='screenmaster',
            name='profiled_country',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='screenmaster',
            name='profiled_full_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='screenmaster',
            name='profiled_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='screenmaster',
            name='profiled_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='screenmaster',
            name='profiled_state',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='screenmaster',
            name='reasoning',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='screenmaster',
            name='ring1',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='screenmaster',
            name='ring2',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='screenmaster',
            name='ring3',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
