# Generated by Django 5.2.11 on 2026-02-21 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xia', '0002_screenmaster_llmmode_screenmaster_llmreason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlotBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.IntegerField(help_text='Source booking ID (mapped from api.id)', unique=True)),
                ('screen_name', models.CharField(blank=True, default='', max_length=255)),
                ('booked_num_slots', models.IntegerField(default=0)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('campaign_id', models.CharField(blank=True, default='', max_length=255)),
                ('user_id', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(blank=True, default='', max_length=50)),
                ('screen_owner', models.CharField(blank=True, default='', max_length=100)),
                ('payment', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True, help_text='Last time this row was synced from source')),
                ('screen', models.ForeignKey(blank=True, db_column='screenid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='xia.screenmaster', to_field='screenid')),
            ],
            options={
                'verbose_name': 'Slot Booking',
                'verbose_name_plural': 'Slot Bookings',
                'db_table': 'xia_slot_booking',
                'ordering': ['-created_at'],
            },
        ),
    ]
