# Generated by Django 5.2.11 on 2026-02-21 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xia', '0003_slotbooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(editable=False, help_text='Auto-generated by XIA on first message', unique=True)),
                ('user_id', models.CharField(help_text='Advertiser user ID (from Studio)', max_length=255)),
                ('campaign_id', models.CharField(help_text='Campaign ID this chat belongs to (from Studio)', max_length=255)),
                ('gateway_start_date', models.CharField(blank=True, default='', max_length=20)),
                ('gateway_end_date', models.CharField(blank=True, default='', max_length=20)),
                ('gateway_location', models.JSONField(blank=True, default=list)),
                ('gateway_budget_range', models.CharField(blank=True, default='', max_length=50)),
                ('active_filters', models.JSONField(blank=True, default=dict, help_text='Current filters applied by XIA on top of gateway')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chat Session',
                'verbose_name_plural': 'Chat Sessions',
                'db_table': 'xia_chat_session',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10)),
                ('content', models.TextField()),
                ('screens_returned', models.JSONField(blank=True, help_text='Screen IDs returned in this response (assistant only)', null=True)),
                ('filters_applied', models.JSONField(blank=True, help_text='Filters that were active for this response', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(db_column='session_id', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='xia.chatsession', to_field='session_id')),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'db_table': 'xia_chat_message',
                'ordering': ['created_at'],
            },
        ),
    ]
