# Generated by Django 5.2.11 on 2026-02-23 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xia', '0004_chatsession_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='messages',
            field=models.JSONField(blank=True, default=list, help_text='Conversation history as JSON array'),
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
