# Generated by Django 5.2.11 on 2026-02-23 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xia', '0005_chatsession_messages_delete_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='ad_category',
            field=models.CharField(blank=True, default='', help_text='What user is advertising: healthcare, alcohol, etc.', max_length=100),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='brand_objective',
            field=models.CharField(blank=True, default='', help_text='awareness, store_visit, product_launch, or offer_based', max_length=30),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='detected_persona',
            field=models.CharField(blank=True, default='', help_text='agency or business_owner — auto-detected by Call #1', max_length=20),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='pending_gateway_edits',
            field=models.JSONField(blank=True, default=dict, help_text='Gateway changes awaiting user confirmation'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='pending_questions',
            field=models.JSONField(blank=True, default=list, help_text='Questions queued by Call #1 — shown one at a time'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='persona_confidence',
            field=models.FloatField(default=0.0, help_text='Confidence score 0.0-1.0 for persona stability (anti-flickering)'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='product_category',
            field=models.CharField(blank=True, default='', help_text='One of 12 master groups: fashion_apparel, jewellery_luxury, etc.', max_length=50),
        ),
    ]
