# Generated by Django 5.2.11 on 2026-02-24 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xia', '0006_chatsession_ad_category_chatsession_brand_objective_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='question_attempts',
            field=models.JSONField(blank=True, default=dict, help_text='Tracks how many times each question topic was asked: {"ad_category": 1, "audience": 2}'),
        ),
    ]
