# Generated by Django 5.2.11 on 2026-02-24 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xia', '0007_add_question_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='discovery_complete',
            field=models.BooleanField(default=False, help_text='True when all 3 core questions answered (ad_category, brand_objective, target_audience)'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='target_audience',
            field=models.CharField(blank=True, default='', help_text='Who the ad targets: young professionals, families, students, etc.', max_length=200),
        ),
    ]
