# Generated by Django 5.2.11 on 2026-02-24 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xia', '0008_question_pipeline_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='previous_filters',
            field=models.JSONField(blank=True, default=dict, help_text='Snapshot of active_filters before last change, used for revert intent'),
        ),
    ]
