# Generated by Django 5.2.11 on 2026-02-24 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xia', '0009_previous_filters_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenmaster',
            name='scheduled_block_date',
            field=models.DateField(blank=True, help_text='Date when SCHEDULED_BLOCK screen will auto-transition to BLOCKED', null=True),
        ),
    ]
