# Generated by Django 5.2.11 on 2026-02-25 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xia', '0010_scheduled_block_date_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='last_intent',
            field=models.CharField(blank=True, default='', help_text='Last detected intent from Call #1', max_length=50),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='last_question_to_ask',
            field=models.CharField(blank=True, default='', help_text='Last question_to_ask for the user', max_length=500),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='last_quick_replies',
            field=models.JSONField(blank=True, default=list, help_text='Last quick_replies from Call #3'),
        ),
    ]
