# Generated by Django 5.2.11 on 2026-02-25 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xia', '0011_chatsession_last_intent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='last_turn_debug',
            field=models.JSONField(blank=True, default=dict, help_text='Full debug meta from the most recent turn (call1/2/3 meta, discover, screens, etc.)'),
        ),
    ]
