# Generated by Django 5.2.11 on 2026-02-27 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xia', '0012_chatsession_last_turn_debug'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='last_page_context',
            field=models.JSONField(blank=True, default=dict, help_text='Last page_context sent by Studio (page, page_label, summary, data)'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='mode',
            field=models.CharField(default='normal', help_text='Session mode: "normal" (gateway flow) or "live" (context-aware)', max_length=10),
        ),
    ]
