# Generated by Django 6.0.1 on 2026-02-13 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('console', '0031_screenspec_is_profiled'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreenProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=9, max_digits=12)),
                ('longitude', models.DecimalField(decimal_places=9, max_digits=12)),
                ('mode', models.CharField(default='hybrid', help_text='hybrid or rules', max_length=20)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city_tier', models.CharField(blank=True, max_length=20)),
                ('formatted_address', models.TextField(blank=True)),
                ('primary_type', models.CharField(blank=True, help_text='e.g. MIXED_BIASED, COMMERCIAL', max_length=50)),
                ('area_context', models.CharField(blank=True, help_text='e.g. Mixed Use (primarily Banking / Finance Zone)', max_length=255)),
                ('confidence', models.CharField(blank=True, help_text='high, medium, low', max_length=20)),
                ('classification_detail', models.CharField(blank=True, help_text='e.g. STRONG_BIAS_TOWARD_FINANCE', max_length=100)),
                ('dominant_group', models.CharField(blank=True, help_text='e.g. FINANCE, RETAIL', max_length=50)),
                ('movement_type', models.CharField(blank=True, help_text='e.g. SLOW_FLOW, PEDESTRIAN', max_length=50)),
                ('movement_context', models.CharField(blank=True, help_text='e.g. Internal Connector Road', max_length=255)),
                ('dwell_category', models.CharField(blank=True, help_text='e.g. MEDIUM_WAIT', max_length=50)),
                ('dwell_confidence', models.FloatField(blank=True, null=True)),
                ('dwell_score', models.FloatField(blank=True, null=True)),
                ('dominance_ratio', models.FloatField(blank=True, null=True)),
                ('ring1_analysis', models.JSONField(blank=True, help_text='Ring 1: authority detection (r=75m)', null=True)),
                ('ring2_analysis', models.JSONField(blank=True, help_text='Ring 2: area classification (r=450-500m)', null=True)),
                ('ring3_analysis', models.JSONField(blank=True, help_text='Ring 3: movement context (r=200m)', null=True)),
                ('reasoning', models.JSONField(blank=True, default=list, help_text='Step-by-step reasoning logs')),
                ('llm_used', models.BooleanField(default=False)),
                ('llm_reason', models.CharField(blank=True, help_text='e.g. RULES_SUFFICIENT', max_length=100)),
                ('llm_mode', models.CharField(blank=True, help_text='hybrid or rules', max_length=20)),
                ('profiled_at', models.DateTimeField(blank=True, help_text='When the engine computed this', null=True)),
                ('api_calls_made', models.IntegerField(default=0)),
                ('cached', models.BooleanField(default=False)),
                ('processing_time_ms', models.IntegerField(blank=True, null=True)),
                ('api_key_configured', models.BooleanField(default=True)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('version', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('screen', models.OneToOneField(help_text='One-to-one link to the screen', on_delete=django.db.models.deletion.CASCADE, related_name='ai_profile', to='console.screenspec')),
            ],
            options={
                'verbose_name': 'Screen AI Profile',
                'verbose_name_plural': 'Screen AI Profiles',
                'db_table': 'screen_ai_profiles',
            },
        ),
    ]
