# Generated by Django 6.0.2 on 2026-02-27 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('campaign_id', models.CharField(editable=False, help_text='Auto-generated: 3-letter name + 3-letter location + unique number', max_length=20, primary_key=True, serialize=False)),
                ('campaign_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('booked_screens', models.JSONField(default=dict, help_text='Map of screen_id → slot_count')),
                ('price_snapshot', models.JSONField(default=dict, help_text='Map of screen_id → price_per_slot at booking time')),
                ('total_slots_booked', models.IntegerField(default=0)),
                ('total_budget', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('budget_range', models.DecimalField(decimal_places=2, default=0, help_text='Gate budget entered by user', max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studio_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScreenBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('screen_slots', models.JSONField(default=list, help_text='List of {screen_id, screen_name, slots[]} objects')),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Suggestion Ready', 'Suggestion Ready')], default='Draft', max_length=50)),
                ('creative_suggestion_url', models.URLField(blank=True, default=None, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundles', to='studio.campaign')),
            ],
            options={
                'verbose_name': 'Screen Bundle',
                'verbose_name_plural': 'Screen Bundles',
                'ordering': ['created_at'],
            },
        ),
    ]
